# Generated by Django 4.2.27 on 2026-01-18 23:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'amenity',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_hotels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='project_second_lab.amenity')),
            ],
            options={
                'db_table': 'room_type',
                'unique_together': {('title',)},
            },
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('occupied_units', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room_types', to='project_second_lab.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_variants', to='project_second_lab.roomtype')),
            ],
            options={
                'db_table': 'hotel_room_type',
                'unique_together': {('hotel', 'room_type')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_from', models.DateField()),
                ('stay_to', models.DateField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('hotel_room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project_second_lab.hotelroomtype')),
            ],
            options={
                'db_table': 'review',
                'indexes': [models.Index(fields=['hotel_room_type', 'created_at'], name='review_hotel_r_f0e665_idx'), models.Index(fields=['rating'], name='review_rating_d6a32f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('CANCELED', 'Canceled')], default='BOOKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_check_in', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('hotel_room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='project_second_lab.hotelroomtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservation',
                'indexes': [models.Index(fields=['hotel_room_type', 'check_in', 'check_out'], name='reservation_hotel_r_2128e3_idx'), models.Index(fields=['status', 'check_in'], name='reservation_status_264d85_idx')],
            },
        ),
    ]
